id: P49CC91FC
initial_creation_type: ocr
source_metadata:
  volumes:
    b45138ab9fd7465d9f3c0f143f3edeba:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: དཔལ་འབྱུང་པོ་འདུལ་བྱེད་ཀྱི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག།
      total_pages: 1379
      volume_number: 37
