id: DAC3ECB8C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-19T04:53:50+00:00'
last_modified: '2022-05-26T12:24:20.029757+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '1026':
      image_group_id: I1PD95882
      title: དཔལ་འབྱུང་པོ་འདུལ་བྱེད་ཀྱི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག།
      total_pages: 1379
      order: 37
      base_file: 1026.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
